### ISSUE TITLE
Diagramme UML

### ISSUE THREAD

**Issue by ThomasLEBRET** [solennement/ESILV-#1]
# Suivi du diagramme UML

- Où en es-tu ?
- As-tu besoin d'aide ?
- Si tu as besoin d'aide, qu'est ce que tu ne comprends pas ?

**Comment by solennement** [comment]
voici
[uml.pdf](https://github.com/solennement/ESILV-/files/5857854/uml.pdf)

**Comment by ThomasLEBRET** [comment]
Alors je suis pas tout à fait d'accord. 
Il manque 
- les get 
- les set 

Pourquoi il y a l'entité Fiche client liée à commande ? C'est quoi l'entité Commis ?

**Comment by solennement** [comment]
ou ca ? on les met pas nous dedans donc jsp
commis cest celui qui prend la commande et receptionne la facture. et client commande car cest le client qui la passe sa commande

**Comment by solennement** [comment]
[Uploading ClubTennisVersion3.pdf…]()

**Comment by solennement** [comment]
Voici l'uml que jai refais
[UML.pdf](https://github.com/solennement/ESILV-/files/5862157/UML.pdf)

**Comment by solennement** [comment]
[Uploading UML.pdf…]()
